[package]
name = "psql_project"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
inquire = "0.6.1"
native-tls = "0.2.11"
postgres = "0.19.5"
postgres-native-tls = "0.5.0"
